<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/24 14:18:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'pa$$',
  'name' => 'doctrine',
)),);
